modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/Scarecrows/blob/1.21.4/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Scarecrows/issues"

[[mods]]
	modId="scarecrows"
	version="${file.jarVersion}"
	displayName="Scarecrows"
	description='''Adds scarecrows that keep monsters (and animals if you want) off your lawn.'''
	displayURL="http://curseforge.com/minecraft/mc-mods/scarecrows"
	authors="bl4ckscor3"

[[dependencies.scarecrows]]
    modId="neoforge"
    type="required"
    versionRange="[21.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scarecrows]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4,1.22)"
    ordering="NONE"
    side="BOTH"